### ISSUE TITLE
Can't find server.json

### ISSUE THREAD

**Issue by yusuffachroni** [Cyclonecode/mysql-notification#1]
i couldn't find server.json, and when i run npm server.js, i got this error 

Mon Apr 30 2018 10:19:21 GMT+0700 (WIB) Server is listening on port 999
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:999
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1277:14)
    at listen (net.js:1313:10)
    at net.js:1423:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:613:11)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

**Comment by Cyclonecode** [comment]
@yusuffachroni - Did you manage to solve it? Please share what you did if there was any problem testing this repository.

**Comment by yusuffachroni** [comment]
i make my own socket server :p
